myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('posts/', views.posts_index, name = 'posts_index'),
    path('posts/<int:post_id>/', views.posts_show, name = 'posts_show'),
    path('authors/', views.authors_index, name = 'authors_index'),
    path('authors/<int:author_id>', views.authors_show, name = 'authors_show'),
    path('enquire/', views.enquire, name = 'enquire'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog import views

urlpatterns = [
    path('myblog/', include('myblog.urls')),
    path('admin/', admin.site.urls),
    
]

myblog/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length = 200)
    email = models.EmailField('email address')
    date_joined = models.DateTimeField('date joined', auto_now_add = True)
    about = models.TextField()

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    post_title = models.CharField(max_length = 200)
    post_content = models.TextField()
    date_updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.post_title

class Enquirer(models.Model):
    pass

myblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Author

# Posts

# R - Read All (index)
def posts_index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'myblog/posts/index.html', context)

# R - Read One (show)
def posts_show(request, post_id):
    post = get_object_or_404(Post, id = post_id)
    posts = Post.objects.filter(author__id = post.author.id)
    context = {
        'post': post,
        'posts': posts
    }
    return render(request, 'myblog/posts/show.html', context)

# Authors

# R - Read All (index)
def authors_index(request):
    authors = Author.objects.all()
    context = {
        'authors': authors
    }
    return render(request, 'myblog/authors/index.html', context)

# R - Read One (show)
def authors_show(request, author_id):
    author = get_object_or_404(Author, id = author_id)
    posts = Post.objects.filter(author__id = author_id).order_by('-date_updated')
    context = {
        'author': author,
        'posts': posts
    }
    return render(request, 'myblog/authors/show.html', context)

# Others

def enquire(request):
    authors = Author.objects.all()
    context = {
        'author': authors
    }
    return render(request, "myblog/enquire.html", context)

# Home
def home(request):
    return render(request, 'myblog/home.html')

myblog/templates/myblog/authors/index.html
{% extends "../base.html" %}

{% block title %}

{% endblock %}

{% block content %}
<div class="container" >
    <div class="section" >
        <ul class="collection with-header">
            <li class="collection-header grey lighten-3">
                <h3>List of Authors</h3>
                <p>Check out below all the contributing authors on this blog!</p>
            </li>
            {% if authors %}
                {% for author in authors %}
                <a href="{% url 'myblog:authors_show' author.id %}" class="collection-item" >
                    <span class="right" >Post count: {{ author.post_set.all.count }}</span>
                    <span>
                        <i class="material-icons small left" >developer_mode</i>
                        {{ author.name }}
                    </span>
                </a>
                {% endfor %}
            {% else %}
            <li class="collection-item" >
                There is no author for this blog yet
            </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

myblog/templates/myblog/authors/show.html
{% extends "../base.html" %}

{% block title %}
<title>{{ author.name }}</title>
{% endblock %}

{% block content %}

<div class="container" >
    <!-- To contaain Aurthor's information -->
    <div class="section" >
        <div class="card" >
            <div class="card-content grey lighten-3" >
                <span class="right" >Member since: {{ author.date_joined.date }}</span>
                <h3>{{ author.name }}</h3>
                <p>Email: <a href="mailto:{{ author.email }}">{{ author.email }}</a> </p>
                <blockquote> <p>{{ author.about }}</p> </blockquote>
            </div>
        </div>
    </div>
    <!-- Lists out Author's posts -->
    <ul class="collection with-header" >
        <li class="collection-header blue lighten-4">
            <h6>Posts by {{ author.name }}</h6>
        </li>
    </ul>
    {% if posts %}
        {% for post in posts %}
        <a href="{% url 'myblog:authors_show' post.id %}" class="collection-item black-text">
            <span class="right grey-text" >
                Last Updated: {{ post.date_updated }}
            </span>
            <h6>
                {{ post.post_title }}
            </h6>
            <p>
                {{ post.post_content | truncatewords:10 }}
            </p>
        </a>
        {% endfor %}
    {% else %}
        <li class="collection-item" >This author has not created any posts yet.</li>
    {% endif %}
</div>


{% endblock %}

myblog/templates/myblog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Base Page</title>
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block stylesheet %}

    {% endblock %}
</head>

<body>
    <!-- Navbar -->
    <nav>
        <div class="nav-wrapper container">
            <a href="{% url 'myblog:home' %}" class="brand-logo valign-wrapper">
                <i class="material-icons left">cloud</i>
                My Blog
            </a>
            <ul id="nav-mobile" class="right">
                <li>
                    <a href="{% url 'myblog:posts_index' %}" class="valign-wrapper">
                        <i class="material-icons left">content_copy</i>
                        Posts
                    </a>
                </li>
                <li>
                    <a href="{% url 'myblog:authors_index' %}" class="valign-wrapper">
                        <i class="material-icons left">create</i>
                        Authors
                    </a>
                </li>
                <li>
                    <a href="{% url 'myblog:enquire' %}" class="valign-wrapper">
                        <i class="material-icons left">email</i>
                        Contact Author
                    </a>
                </li>
            </ul>
        </div>
    </nav><!-- /Navbar -->

    {% block content %}

    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    {% block javascript %}

    {% endblock %}
</body>

</html>

myblog/templates/myblog/enquire.html
{% extends "./base.html" %}

{% block title %}
<title>Contact Author</title>
{% endblock %}

{% block content %}

<div class="centerPage">
    <h1>Leave me a message here</h1>
    
    <div class="row">
        <form action="" method="post" class="col s12">
            <div class="row">
                <div class="input-field col s6">
                    <label for="author">Select Author</label>
                    <select name="author" id="author">
                        {% for author in authors %}
                        <option value="{{ author }}">{{ author }}</option>
                        {% endfor %}
                    </select>
    
                </div>
                <!-- firstname -->
                <div class="input-field col s6">
                    <label for="firstName">First Name</label>
                    <input placeholder="John" name="firstName" id="firstName" type="text" class="validate">
                </div>
                <!-- lastname -->
                <div class="input-field col s6">
                    <label for="lastName">Last Name</label>
                    <input placeholder="Doe" name="lastName" id="lastName" type="text" class="validate">
                </div>
                <!-- email -->
                <div class="input-field col s6">
                    <label for="email">Email</label>
                    <input placeholder="john@doe.com.au" name="email" id="email" type="email" class="validate">
                </div>
                <!-- Message -->
                <div class="input-field col s12">
                    <label for="message">Message</label>
                    <textarea placeholder="Hello John,.." name="message" id="message" class="materialize-textarea" cols="30"
                        rows="10"></textarea>
                </div>
    
                <!-- action Buttons -->
                <button class="btn waves-effect waves-light">
                    Send Enquiry
                    <i class="material-icons right">send</i>
                </button>
                <button class="btn waves-effect waves-light">
                    Clear
                    <i class="material-icons right">undo</i>
                </button>
    
            </div>
        </form>
    </div>
</div>








{% endblock %}

myblog/templates/myblog/home.html
{% extends './base.html' %}

{% load static %}

{% block title %}
    <title>Homepage</title>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="parallax-container">
            <div class="parallax"><img src="{% static 'images/scene1.jpg' %}"></div>
        </div>
        <div class="section white">
            <div class="row container">
                <h1 class="header">My Blog</h1>
                <p class="grey-text text-darken-3 lighten-3">
                    Welcome to my blog! Click below to check out the latest cool posts!
                </p>
                <a href="{% url 'myblog:posts_index' %}" class="btn-large">View posts</a>
            </div>
        </div>
        <div class="parallax-container">
            <div class="parallax"><img src="{% static 'images/scene2.jpg' %}"></div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

myblog/templates/myblog/posts/index.html
{% extends '../base.html' %}

{% block title %}
    <title>Posts</title>
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Showing All Posts</h2>
        {% for post in posts %}
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            <span class="right">
                                Last updated: {{ post.date_updated }}
                            </span>
                            <span class="card-title">
                                {{ post.post_title }}
                            </span>
                            <span class="right">
                                Author: {{ post.author }}
                            </span>
                            <p>{{ post.post_content | truncatewords:30 }}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'myblog:posts_show' post.id %}">See Inside</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

myblog/templates/myblog/posts/show.html
{% extends '../base.html' %}

{% load static %}

{% block title %}
    <title>{{ post.post_title }}</title>
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/posts_show.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <!-- Post Details -->
            <div class="col s9">
                <div class="section">
                    <h2>{{ post.post_title }}</h2>
                    <h6 class="grey-text">
                        {{ post.date_updated.date }} By 
                        <a href="{% url 'myblog:authors_show' post.author.id %}">
                            {{ post.author.name}}
                        </a>
                    </h6>
                </div>
                <div class="divider"></div>
                <div class="section">
                    <p>{{ post.post_content }}</p>
                </div>
            </div> <!-- /Post Details -->

            <!-- About Author -->
            <div class="col s3">
                <div class="section">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">About Author</span>
                            <p>{{ post.author.about }}</p>
                        </div>
                    </div>
                </div>
                <div class="section left-padded">
                    <h5>{{ post.author.name }}'s Posts</h5>
                    <ul>
                        {% for post in posts %}
                            <li><a href="{% url 'myblog:posts_show' post.id %}">{{ post.post_title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="section left-padded">
                    <h5>Contact</h5>
                    <a href="mailto:{{ post.author.email }}">{{ post.author.email }}</a>
                </div>
            </div> <!-- /About Author -->
        </div>
    </div>
{% endblock %}